# Generated by Django 4.2.7 on 2023-11-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('njp', '0002_pic_photo_thumb_nail'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.AddField(
            model_name='pic',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='pic_likes', to='njp.ipmodel'),
        ),
    ]
